/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PocCta {
        "text": string;
        "variant": string;
    }
}
declare global {
    interface HTMLPocCtaElement extends Components.PocCta, HTMLStencilElement {
    }
    var HTMLPocCtaElement: {
        prototype: HTMLPocCtaElement;
        new (): HTMLPocCtaElement;
    };
    interface HTMLElementTagNameMap {
        "poc-cta": HTMLPocCtaElement;
    }
}
declare namespace LocalJSX {
    interface PocCta {
        "text"?: string;
        "variant"?: string;
    }
    interface IntrinsicElements {
        "poc-cta": PocCta;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "poc-cta": LocalJSX.PocCta & JSXBase.HTMLAttributes<HTMLPocCtaElement>;
        }
    }
}
